-- INT; DECIMAL(N,M),VARCHAR(M), 
-- BLOB, DATE "YYY-MM-DD", TIMESTAMP "YYYY-MM-DD  HH:MM:SS" 
--  PRIMARY KEY ; AUTO_INCREMENT NOT NULL DEFAULT uniQ
-- FOREIGN KEY ,REFERENCES  ON DELETE   SET NULL  
CREATE TABLE customer(
cus_id INT PRIMARY KEY AUTO_INCREMENT,
first_name VARCHAR(50) NOT NULL,
Family_name VARCHAR(50)  NOT NULL,
birthday DECIMAL(5,2)  NOT NULL,
points int DEFAULT 0











)