-- INT; DECIMAL(N,M),VARCHAR(M), 
-- BLOB, DATE "YYY-MM-DD", TIMESTAMP "YYYY-MM-DD  HH:MM:SS" 
--  PRIMARY KEY ; AUTO_INCREMENT NOT NULL DEFAULT uniQ
-- FOREIGN KEY ,REFERENCES  ON DELETE   SET NULL  
CREATE TABLE orderss(
order_id INT PRIMARY KEY AUTO_INCREMENT,
product VARCHAR(50)  NOT NULL,
price DECIMAL(5,2)  NOT NULL,
CUS_ID INT ,
FOREIGN KEY ( CUS_ID) REFERENCES customer( CUS_ID ) ON DELETE set null









)